import fs from 'fs'; import os from 'os'; import path from 'path'; import {fileURLToPath,pathToFileURL} from 'url';
// ورکر فایل .js با export است؛ برای import بی‌هشدار، یک کپی .mjs
const here=path.dirname(fileURLToPath(import.meta.url)), tmp=path.join(os.tmpdir(),'sd-worker-'+process.pid+'.mjs');
fs.copyFileSync(path.join(here,'..','proxy','worker.js'),tmp);
const W=(await import(pathToFileURL(tmp).href)).default;
let bad=0;const ok=(c,m)=>{if(!c)bad++;console.log('  '+(c?'✅':'❌')+' '+m);};
const kv=new Map();const STORE={get:async k=>kv.has(k)?kv.get(k):null,put:async(k,v)=>kv.set(k,v),delete:async k=>kv.delete(k)};
const env={STORE,SYNC_TOKEN:'sec',TG_BOT_TOKEN:'123:abc'};
const sent=[];let mark={BTC:89.5,ETH:3000,SOL:160};let binanceDown=false;
globalThis.fetch=async(u,o)=>{u=String(u);const J=(b,s)=>new Response(JSON.stringify(b),{status:s||200});
  if(u.includes('api.telegram.org')){const m=u.split('/').pop();const body=JSON.parse(o.body);
    if(m==='getUpdates')return J({ok:true,result:[{message:{chat:{id:777,type:'private',first_name:'Ali'},text:'/start'}}]});
    if(m==='sendMessage'){sent.push(body);return J({ok:true});}}
  if(u.includes('fapi.binance.com'))return binanceDown?J({},451):J(Object.entries(mark).map(([k,v])=>({symbol:k+'USDT',markPrice:String(v)})).concat(Array.from({length:30},(_,i)=>({symbol:'Z'+i+'USDT',markPrice:'1'}))));
  if(u.includes('okx.com'))return J({data:Object.entries(mark).map(([k,v])=>({instId:k+'-USDT-SWAP',markPx:String(v)})).concat(Array.from({length:30},(_,i)=>({instId:'Z'+i+'-USDT-SWAP',markPx:'1'})))});
  if(u.includes('api.binance.com'))return J([{symbol:'BTCUSDT',price:'90.5'},{symbol:'SOLUSDT',price:'158'}].concat(Array.from({length:30},(_,i)=>({symbol:'Z'+i+'USDT',price:'1'}))));
  if(u.startsWith('https://t.me/s/'))return new Response(TME,{status:200});
  return J({},404);};
let TME='<html></html>';
const tmePost=(n,t)=>'<div class="tgme_widget_message" data-post="ccoineres/'+n+'"><div class="tgme_widget_message_text js-message_text" dir="auto">'+t+'</div><div class="tgme_widget_message_footer"></div></div>';
const req=(path,tok)=>new Request('https://w.dev'+path,{method:'POST',headers:{Authorization:'Bearer '+(tok||'sec')}});
const call=async(p,t)=>(await W.fetch(req(p,t),env)).json();
const db={rev:3,at:1,data:{settings:{feat:{alerts:true}},positions:[
  {id:'a',ticker:'BTC',dir:'long',kind:'futures',entry:100,stop:90,lev:5,margin:10,status:'open'},
  {id:'b',ticker:'ETH',dir:'long',kind:'futures',entry:2800,stop:2700,lev:3,margin:10,status:'open',pbc:0,pb:{parts:[0.5,0.5,0],be:1,trail:false,tps:[2950,3100,3300]}},
  {id:'c',ticker:'SOL',dir:'long',kind:'spot',entry:150,stop:140,lev:1,margin:10,status:'open',targets:[155,170]},
  {id:'d',ticker:'BTC',dir:'long',kind:'futures',entry:100,stop:80,lev:5,margin:10,status:'closed'}]}};
kv.set('signaldesk',JSON.stringify(db));
console.log('=== وصل کردن ===');
ok((await call('/tg/link','bad')).error==='unauthorized','بدون رمز درست رد می‌شود');
const l=await call('/tg/link');
ok(l.linked&&JSON.parse(kv.get('signaldesk:tg')).chat===777,'شناسه‌ی چت از getUpdates پیدا و ذخیره شد');
ok(sent.length===1&&sent[0].text.includes('وصل شد'),'پیام «وصل شد» رفت');
ok((await call('/tg/status')).linked,'وضعیت: وصل');
console.log('=== بررسی دقیقه‌ای ===');
sent.length=0;
await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
const txt=sent.map(s=>s.text);console.log('   '+txt.join('\n   ').replace(/\n/g,' / '));
ok(txt.some(t=>t.startsWith('🔴 BTC')&&t.includes('مارک: 89.5')),'BTC فیوچرز: مارک 89.5 زیر استاپ 90 ← پیام حد ضرر');
ok(txt.some(t=>t.startsWith('🟢 ETH')&&t.includes('تارگت 1')&&t.includes('ببند 50٪')&&t.includes('استاپ ← ورود')),'ETH: پله‌ی ۱ نقشه با متن «ببند 50٪ · استاپ ← ورود»');
ok(txt.some(t=>t.startsWith('🟢 SOL')&&t.includes('تارگت 1')),'SOL اسپات بدون نقشه: تارگت 1 با قیمت اسپات');
ok(!txt.some(t=>t.includes('تارگت 2')),'تارگت 2 سولانا نرسیده');
ok(sent.length===3,'پوزیشن بسته هیچ پیامی ندارد؛ جمعاً ۳');
sent.length=0;
await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
ok(sent.length===0,'دقیقه‌ی بعد: تکراری نمی‌فرستد');
console.log('=== جابه‌جایی استاپ و منبع جایگزین ===');
db.data.positions[0].stop=89;kv.set('signaldesk',JSON.stringify(db));binanceDown=true;mark.BTC=89.2;
await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
ok(sent.some(s=>s.text.startsWith('🟠 BTC')),'استاپ عوض شد (89): هشدار تازه «نزدیک حد ضرر» با مارک OKX وقتی بایننس بسته است');
console.log('=== وقتی برنامه بسته است: سیگنال تازه، مهلت ===');
TME='<html>'+tmePost(500,'#BTC لانگ<br>ورود 100<br>حد ضرر 95')+'</html>';
db.data.settings.riskUsd=2;db.data.settings.maxLev=10;db.data.positions[1].until=Date.now()-1000;kv.set('signaldesk',JSON.stringify(db));
sent.length=0;await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
ok(!sent.some(s=>s.text.startsWith('📣'))&&kv.get('signaldesk:tgseen')==='500','بار اول: پست‌های موجود فقط یادداشت می‌شوند، نه پیام');
ok(sent.some(s=>s.text.startsWith('⏱ ETH')&&s.text.includes('مهلت پوزیشن تمام شد')),'مهلت پوزیشن ETH تمام شد ← پیام');
TME='<html>'+tmePost(500,'#BTC لانگ<br>ورود 100<br>حد ضرر 95')+tmePost(501,'#SOL لانگ<br>ورود ۱۵۰<br>حد ضرر ۱۴۵<br>تارگت ۱۶۰')+tmePost(502,'🟢 #BTC Liquidated Short: $89K')+tmePost(503,'یک نکته‌ی آموزشی')+'</html>';
sent.length=0;await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
const ns=sent.filter(s=>s.text.startsWith('📣'));console.log('   '+ns.map(s=>s.text.replace(/\n/g,' / ')).join('\n   '));
ok(ns.length===1&&ns[0].text.includes('#SOL')&&ns[0].text.includes('ایزوله 10x · مارجین $5.83')&&ns[0].text.includes('t.me/ccoineres/501'),'پست تازه‌ی سیگنال ← پیام با اندازه‌ی ایزوله؛ لیکوئید و نکته نه');
sent.length=0;await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
ok(sent.length===0,'دقیقه‌ی بعد: نه سیگنال تکراری، نه مهلت تکراری');
db.data.settings.adv={on:true,cats:{sig:false,pos:true}};kv.set('signaldesk',JSON.stringify(db));
TME='<html>'+tmePost(504,'#ETH شورت<br>ورود 3000<br>حد ضرر 3100')+'</html>';
sent.length=0;await new Promise(r=>W.scheduled({},env,{waitUntil:p=>p.then(r)}));
ok(!sent.some(s=>s.text.startsWith('📣')),'دسته‌ی «سیگنال» در برنامه خاموش ← سیگنال تازه به تلگرام نمی‌رود');
db.data.settings.adv={on:false};kv.set('signaldesk',JSON.stringify(db));
ok((await call('/tg/check')).skipped==='alerts-off','مشاور در برنامه خاموش ← ورکر هم ساکت');
ok((await call('/tg/unlink')).linked===false&&!kv.has('signaldesk:tg'),'قطع کردن');
console.log(bad?'✗ '+bad:'✔ همه درست');
